// Auto-generated by src/scripts/generate-manifest.ts

export type MDX = {
  title: string;
  contributors?: string[];
  created_at?: string;
  updated_at?: string;
};

export type MarkdownItems = Record<string, MDX>;

export const helpManifest: MarkdownItems = {
  '/help/': {
    title: 'Getting Started',
  },
  '/help/ranks/': {
    title: 'Ranks',
  },
  '/help/preventing_grief/': {
    title: 'Preventing Grief',
  },
  '/help/faq/': {
    title: 'FAQ',
  },
  '/help/proximity_chat/': {
    title: 'Proximity Chat',
  },
  '/help/terms_and_conditions/': {
    title: 'Terms and Conditions',
  },
  '/help/support/': {
    title: 'Support',
  },
  '/help/community/': {
    title: 'Community',
  },
  '/help/economy/': {
    title: 'Economy',
  },
  '/help/suggestions/': {
    title: 'Suggestions',
  },
};
